import { type NextPage } from "next";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

const SecretMasterPlan: NextPage = () => {
  return (
    <main>
      <Navbar />

      <section className="min-h-screen flex flex-col items-center justify-center px-6 pt-20">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tighter mt-16 mb-4 text-center">
            The Secret Own Protocol Master Plan
          </h1>
          <p className="text-xl sm:text-2xl font-bold  text-center mb-2">
            (Just between you & me)
          </p>
          <p className="text-sm text-gray-400 text-center mb-12">
            Bhargav Aparoksham, Core Contributor, Own Protocol DAO, 15 Dec 2024.
          </p>
          <article className="text-black-300 space-y-8">
            <p>
              In the ever-evolving world of decentralized finance (DeFi), the
              journey to bridge real-world assets with blockchain technology has
              been a long-standing ambition. The &quot;Own Protocol&quot; is
              here to turn that ambition into reality. Here is the master plan
              for the world’s first fully decentralized on-chain protocol for
              direct exposure to real-world assets.
            </p>

            <hr className="border-t border-gray-600" />

            <h2 className="text-3xl font-semibold">The Vision</h2>
            <p>
              To create a decentralized financial ecosystem where anyone can
              access, trade, and earn yield from tokenized real-world assets
              like stocks, commodities, fiat, and other liquid instruments — all
              backed by a trustless, transparent, and automated system.
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong>Borderless Finance:</strong> A global financial
                ecosystem unshackled from intermediaries, empowering individuals
                regardless of their location.
              </li>
              <li>
                <strong>24/7 Accessibility:</strong> Access to assets beyond
                market hours or regional restrictions.
              </li>
              <li>
                <strong>Fractional Ownership:</strong> Breaking barriers to
                entry by allowing smaller investments in traditionally
                high-value assets.
              </li>
              <li>
                <strong>Increased Liquidity:</strong> A seamless flow of capital
                across traditional and decentralized markets.
              </li>
              <li>
                <strong>Programmable Yield:</strong> Automating yield generation
                tied to the performance of real-world assets.
              </li>
            </ul>

            <hr className="border-t border-gray-600" />

            <h2 className="text-3xl font-semibold">How Own Protocol Works</h2>
            <p>
              <strong>User Staking:</strong> Users stake stablecoins (USDC) into
              asset-specific pools. Each deposit generates a pool position for
              the corresponding real-world asset. For example, staking $1,000
              USDC in the Tesla pool mints 1,000 xTSLA_USDC tokens, backed by
              equivalent Tesla shares held by an LP.
            </p>
            <p>
              <strong>xToken Mechanics:</strong> Similar to Aave’s aTokens,
              xTokens represent a user’s claim on staked assets. Their value
              scales with the underlying asset’s performance, and users can
              trade them on secondary markets. Unlike aTokens which accrue only
              positive yield, xTokens can accrue negative yield as well.
            </p>
            <p>
              <strong>Liquidity Providers (LPs):</strong> A decentralized
              network of LPs, operating protocol-specific nodes, fulfills the
              pool positions generated by user stakes on traditional exchanges.
              LPs use their own capital to hold positions that mirror the asset
              pools’ stakes. User funds remain securely within the protocol,
              earning yield through lending platforms like Aave. When users
              initiate unstaking, LPs sell the corresponding positions and
              reconcile profits or losses with the protocol on a weekly basis.
            </p>
            <p>
              <strong>LP Staking and Governance:</strong> To participate, LPs
              must stake Own tokens, which grant them the ability to run
              protocol nodes. These nodes automate critical functions such as
              processing pool positions, exchange trading, and profit/loss
              settlements. To ensure compliance and security, zero-knowledge
              (ZK) proofs validate that LPs maintain the required positions.
              Failing to adhere to protocol rules results in LP stake slashing.
            </p>
            <p>
              <strong>Yield Dynamics:</strong>
              <ul className="list-disc pl-6">
                <li>
                  <strong>For Users:</strong> Yield is directly tied to the
                  performance of the underlying asset (e.g., Tesla’s stock
                  price), providing users with exposure to the asset.
                </li>
                <li>
                  <strong>For LPs:</strong> LPs earn multiple streams of
                  revenue, including stablecoin yields from the staked assets in
                  the protocol, LP fees, and staking rewards in Own tokens. This
                  multi-faceted earning model incentivizes LP participation and
                  ensures protocol sustainability.
                </li>
              </ul>
            </p>

            <hr className="border-t border-gray-600" />

            <h2 className="text-3xl font-semibold">Why Own Protocol Matters</h2>
            <p>
              Traditional finance has thrived on exclusivity and intermediaries,
              but the future demands openness, fairness, and efficiency. Own
              Protocol is not just another DeFi protocol; it’s the first step in
              democratizing access to global financial markets.
            </p>

            <hr className="border-t border-gray-600" />

            <h2 className="text-3xl font-semibold">The Master Plan</h2>
            <ol className="list-decimal pl-6 space-y-2">
              <li>Launch a simple yield farm backed by Own Tokens.</li>
              <li>
                Use the funds to build the first pool backed by real assets.
              </li>
              <li>Scale the protocol to every liquid real-world asset.</li>
            </ol>

            <p className="italic text-black-400">
              &quot;Don’t tell anyone.&quot;
            </p>
            <p>
              Credits: This post is inspired by Tesla Master Plan by Elon Musk.{" "}
              <br /> <br />
              To know more, read our docs or join our discord.
            </p>
          </article>
        </div>
      </section>

      <Footer />
    </main>
  );
};

export default SecretMasterPlan;
